src/main/java/kr/co/lotteon/dto/member/CouponDTO.java, src/main/java/kr/co/lotteon/dto/member/EmailAuthenticationDTO.java, src/main/java/kr/co/lotteon/dto/member/MemberDTO.java, src/main/java/kr/co/lotteon/dto/member/PointDTO.java, src/main/java/kr/co/lotteon/dto/member/TermsDTO.java, src/main/java/kr/co/lotteon/entity/member/Coupon.java, src/main/java/kr/co/lotteon/entity/member/Member.java, src/main/java/kr/co/lotteon/entity/member/Point.java, src/main/java/kr/co/lotteon/entity/member/Terms.java, src/main/java/kr/co/lotteon/security/MyUserDetails.java, src/main/java/kr/co/lotteon/security/SecurityConfig.java
member Entity DTO 생성 및 시큐리티 설정
=> member Entity DTO 생성 및 시큐리티 설정

src/main/resources/templates/index.html
=> index thymeleaf

src/main/java/kr/co/lotteon/controller/AdminController.java, src/main/java/kr/co/lotteon/controller/CsController.java, src/main/java/kr/co/lotteon/controller/MemberController.java, src/main/java/kr/co/lotteon/controller/MyController.java, src/main/java/kr/co/lotteon/controller/PolicyController.java, src/main/java/kr/co/lotteon/controller/ProductController.java
=> Mapping All

src/main/java/kr/co/lotteon/dto/cs/BoardCateDTO.java, src/main/java/kr/co/lotteon/dto/cs/BoardDTO.java, src/main/java/kr/co/lotteon/dto/cs/BoardFileDTO.java, src/main/java/kr/co/lotteon/dto/cs/BoardTypeDTO.java, src/main/java/kr/co/lotteon/dto/cs/CsPageRequestDTO.java, src/main/java/kr/co/lotteon/dto/cs/CsPageResponseDTO.java, src/main/java/kr/co/lotteon/entity/cs/BoardCateEntity.java, src/main/java/kr/co/lotteon/entity/cs/BoardEntity.java, src/main/java/kr/co/lotteon/entity/cs/BoardFileEntity.java, src/main/java/kr/co/lotteon/entity/cs/BoardTypeEntity.java, src/main/resources/templates/cs/index.html, src/main/resources/templates/cs/layout.html
=> kwangeun/cs DTO

.github/workflows/deploy.yml, CI_CD 작업 순서.txt, appspec.yml, scripts/deploy.sh
=> cicd setting

src/main/generated/kr/co/lotteon/entity/product/QProduct.java, src/main/java/kr/co/lotteon/config/WebMvcConfig.java, src/main/java/kr/co/lotteon/controller/MainController.java, src/main/java/kr/co/lotteon/dto/product/PageRequestDTO.java, src/main/java/kr/co/lotteon/dto/product/PageResponseDTO.java, src/main/java/kr/co/lotteon/interceptor/AppInfoInterceptor.java, src/main/java/kr/co/lotteon/repository/product/ProductRepository.java, src/main/java/kr/co/lotteon/service/ProductService.java, src/main/resources/templates/layout/adminLayout.html, src/main/resources/templates/layout/indexLayout.html, src/main/resources/templates/layout/memberLayout.html, src/main/resources/templates/layout/productLayout.html
=> product list ing

src/main/java/kr/co/lotteon/controller/CsController.java, src/main/java/kr/co/lotteon/repository/cs/CsRepository.java, src/main/java/kr/co/lotteon/service/cs/CsService.java, src/main/resources/templates/cs/notice/list.html
csController, csService, html, 레파지토리 수정
=> csController, csService

src/main/java/kr/co/lotteon/controller/MemberController.java, src/main/java/kr/co/lotteon/service/TermsService.java, src/main/resources/templates/member/join.html, src/main/resources/templates/member/signup.html
=> terms 체크박스 스크립트 구현

src/main/java/kr/co/lotteon/controller/MemberController.java, src/main/java/kr/co/lotteon/repository/member/MemberRepository.java, src/main/java/kr/co/lotteon/repository/member/TermsRepository.java, src/main/java/kr/co/lotteon/service/member/MemberService.java, src/main/java/kr/co/lotteon/service/member/TermsService.java, src/main/resources/templates/member/register.html
=> 회원가입 - 유효성 검사 전

.github/workflows/deploy.yml
=> cicd test2

src/main/java/kr/co/lotteon/service/member/MemberService.java, src/main/resources/application.yml, src/main/resources/templates/layout/memberLayout.html, src/main/resources/templates/member/register.html
회원가입 유효성 검사 및 중복검사 - 이메일 인증코드 오류
=> 회원가입 유효성 검사 및 중복검사 - 이메일 인증코드 오류

.github/workflows/deploy.yml, build.gradle
깃허브 액션 버전 변경 테스트 한거 버전 다시 변경, git hub action 실행시 뜨는 경고문 해결 시도
=> version modify and github actions warning 해결

.github/workflows/deploy.yml
=> github action java 배포판 v4

src/main/java/kr/co/lotteon/controller/AdminController.java, src/main/java/kr/co/lotteon/service/AdminService.java, src/main/resources/templates/admin/product/register.html
상품 옵션 기능 구현 완료
상품 테이블에 stock null허용 물어볼 것
=> 상품 옵션 기능 구현

src/main/resources/templates/member/register.html, src/main/resources/templates/member/registerSeller.html
=> 일반회원 회원가입 완료 - 일반회원 level 수정

build.gradle, src/main/generated/kr/co/lotteon/entity/product/QCate3.java, src/main/generated/kr/co/lotteon/entity/product/QProduct.java, src/main/java/kr/co/lotteon/config/WebMvcConfig.java, src/main/java/kr/co/lotteon/dto/product/Cate3DTO.java, src/main/java/kr/co/lotteon/dto/product/ProductDTO.java, src/main/java/kr/co/lotteon/entity/product/Cate3.java, src/main/java/kr/co/lotteon/entity/product/Product.java, src/main/resources/templates/layout/indexLayout.html, src/main/resources/templates/layout/memberLayout.html, src/main/resources/templates/layout/productLayout.html
Product - cate3 추가
Product_cate3 테이블 추가
=> DTO, Entity 수정

src/main/generated/kr/co/lotteon/entity/member/QMember.java, src/main/java/kr/co/lotteon/dto/member/MemberDTO.java, src/main/java/kr/co/lotteon/entity/member/Member.java, src/main/resources/mappers/member.xml, src/main/resources/static/js/checkMember.js, src/main/resources/templates/member/register.html, src/main/resources/templates/member/registerSeller.html
=> 일반 회원가입 - 닉네임 추가

.github/workflows/deploy.yml, build.gradle
=> cicd reset

src/main/java/kr/co/lotteon/dto/admin/BannerDTO.java, src/main/java/kr/co/lotteon/dto/member/PointDTO.java, src/main/java/kr/co/lotteon/dto/product/WishDTO.java, src/main/java/kr/co/lotteon/entity/admin/Banner.java, src/main/java/kr/co/lotteon/entity/product/Option.java, src/main/java/kr/co/lotteon/entity/product/Wish.java
=> add DTO, Entity

src/main/resources/static/js/checkMember.js, src/main/resources/templates/member/register.html
=> 일반회원가입 닉네임 중복 오류 수정

src/main/java/kr/co/lotteon/controller/MemberController.java, src/main/resources/mappers/member.xml, src/main/resources/static/js/checkMember.js, src/main/resources/static/js/checkSeller.js, src/main/resources/templates/member/registerSeller.html
=> 판매자 회원가입 완료

src/main/java/kr/co/lotteon/oauth2/OAuth2UserService.java, src/main/java/kr/co/lotteon/repository/member/MemberRepository.java, src/main/resources/application.yml, src/main/resources/templates/layout/indexLayout.html
=> 인덱스 인가설정 및 로그아웃

src/main/generated/kr/co/lotteon/entity/cs/QBoardFileEntity.java, src/main/java/kr/co/lotteon/oauth2/NaverInfo.java, src/main/java/kr/co/lotteon/oauth2/OAuth2UserService.java, src/main/resources/application.yml, src/main/resources/static/css/member.css, src/main/resources/static/member/images/icon_easy_naver.svg, src/main/resources/templates/layout/memberLayout.html, src/main/resources/templates/member/login.html
=> 소셜 로그인-네이버

src/main/generated/kr/co/lotteon/entity/cs/QBoardFileEntity.java, src/main/resources/templates/layout/productLayout.html, src/main/resources/templates/product/view.html
view page 장바구니 넣기 전 동적으로 처리할 부분
=> view page 동적처리

src/main/java/kr/co/lotteon/config/WebMvcConfig.java, src/main/java/kr/co/lotteon/controller/MainController.java, src/main/java/kr/co/lotteon/repository/custom/ProductRepositoryCustom.java, src/main/java/kr/co/lotteon/repository/impl/ProductRepositoryImpl.java, src/main/java/kr/co/lotteon/service/product/ProductService.java, src/main/resources/application.yml, src/main/resources/templates/index.html, src/main/resources/templates/layout/indexLayout.html, src/main/resources/templates/layout/productLayout.html
=> mainpage, viewpage

src/main/resources/application.yml
=> application uploads오타 수정

src/main/java/kr/co/lotteon/controller/MemberController.java, src/main/java/kr/co/lotteon/mapper/MemberMapper.java, src/main/java/kr/co/lotteon/service/member/MemberService.java, src/main/resources/mappers/member.xml, src/main/resources/static/js/find.js, src/main/resources/templates/member/findId.html, src/main/resources/templates/member/findPass.html, src/main/resources/templates/member/findPassChange.html
=> 비밀번호 찾기 및 변경

src/main/java/kr/co/lotteon/controller/MemberController.java, src/main/java/kr/co/lotteon/security/SecurityConfig.java, src/main/java/kr/co/lotteon/security/SecurityUserService.java, src/main/resources/static/js/rememberId.js, src/main/resources/templates/member/login.html
=> 자동그인 및 아이디 저장 구현

src/main/java/kr/co/lotteon/controller/MemberController.java, src/main/java/kr/co/lotteon/dto/member/MemberDTO.java, src/main/java/kr/co/lotteon/entity/member/Member.java, src/main/java/kr/co/lotteon/security/SecurityConfig.java, src/main/resources/templates/member/signup.html
=> location 선택약관 DB 저장

src/main/resources/static/css/member.css, src/main/resources/templates/member/login.html
=> 소셜 로그인 CSS 수정

src/main/resources/templates/layout/adminLayout.html, src/main/resources/templates/layout/myLayout.html, src/main/resources/templates/layout/policyLayout.html, src/main/resources/templates/layout/productLayout.html, src/main/resources/templates/layout/sellerLayout.html
=> 레이아웃 인가설정 및 매핑

src/main/resources/static/js/checkMember.js, src/main/resources/static/js/checkSeller.js
=> 회원가입-주소, 팩스번호 선택사항 적용

src/main/java/kr/co/lotteon/config/WebMvcConfig.java, src/main/resources/templates/member/findIdResult.html, src/main/resources/templates/member/findPassChange.html, src/main/resources/templates/my/info.html
=> 마이페이지-회원정보 출력 및 마스킹 처리

src/main/resources/static/js/changeInfo.js, src/main/resources/templates/my/info.html
=> 마이페이지-회원정보 수정 스크립트 처리중

src/main/java/kr/co/lotteon/controller/MyController.java, src/main/java/kr/co/lotteon/security/SecurityConfig.java, src/main/java/kr/co/lotteon/service/member/MemberService.java, src/main/resources/static/css/my.css, src/main/resources/static/js/changeInfo.js, src/main/resources/static/js/checkMember.js, src/main/resources/templates/index.html, src/main/resources/templates/layout/csLayout.html, src/main/resources/templates/layout/indexLayout.html, src/main/resources/templates/layout/memberLayout.html, src/main/resources/templates/layout/myLayout.html, src/main/resources/templates/layout/policyLayout.html, src/main/resources/templates/layout/productLayout.html, src/main/resources/templates/my/coupon.html, src/main/resources/templates/my/home.html, src/main/resources/templates/my/info.html, src/main/resources/templates/my/order.html, src/main/resources/templates/my/point.html, src/main/resources/templates/my/qna.html, src/main/resources/templates/my/review.html
=> 마이페이지-회원정보 수정 완료

src/main/java/kr/co/lotteon/controller/MyController.java, src/main/java/kr/co/lotteon/dto/member/MyInfoDTO.java, src/main/java/kr/co/lotteon/repository/cs/BoardRepository.java, src/main/java/kr/co/lotteon/repository/my/CouponRepository.java, src/main/java/kr/co/lotteon/repository/product/OrderItemRepository.java, src/main/java/kr/co/lotteon/service/member/MemberService.java, src/main/java/kr/co/lotteon/service/my/MyService.java, src/main/resources/static/js/myInfo.js, src/main/resources/templates/my/coupon.html
=> 마이페이지-상단바(주문,쿠폰,포인트,문의내역출력)

src/main/java/kr/co/lotteon/config/WebMvcConfig.java, src/main/resources/static/css/common.css, src/main/resources/static/css/product.css, src/main/resources/templates/product/cart.html
=> cart script

src/main/java/kr/co/lotteon/controller/MyController.java, src/main/java/kr/co/lotteon/security/SecurityConfig.java, src/main/java/kr/co/lotteon/service/member/MemberService.java, src/main/java/kr/co/lotteon/service/my/MyService.java, src/main/resources/static/css/my.css, src/main/resources/static/js/changeInfo.js, src/main/resources/templates/layout/myLayout.html, src/main/resources/templates/my/info.html, src/main/resources/templates/my/qna.html
=> 마이페이지-탈퇴하기

src/main/java/kr/co/lotteon/controller/MyController.java, src/main/resources/templates/my/coupon.html
=> 마이페이지-쿠폰 수정

src/main/java/kr/co/lotteon/controller/MyController.java, src/main/java/kr/co/lotteon/repository/cs/BoardRepository.java, src/main/java/kr/co/lotteon/repository/custom/BoardRepositoryCustom.java, src/main/java/kr/co/lotteon/repository/custom/OrderItemRepositoryCustom.java, src/main/java/kr/co/lotteon/repository/impl/BoardRepositoryImpl.java, src/main/java/kr/co/lotteon/repository/impl/OrderItemRepositoryImpl.java, src/main/java/kr/co/lotteon/repository/product/OrderItemRepository.java, src/main/java/kr/co/lotteon/service/my/MyService.java
=> 마이페이지-myInfo 구현완료

src/main/java/kr/co/lotteon/controller/MyController.java, src/main/java/kr/co/lotteon/repository/custom/BoardRepositoryCustom.java, src/main/java/kr/co/lotteon/repository/impl/BoardRepositoryImpl.java, src/main/java/kr/co/lotteon/service/my/MyService.java, src/main/resources/templates/my/qna.html
=> 마이페이지-문의하기페이징 처리

src/main/java/kr/co/lotteon/controller/CartController.java, src/main/java/kr/co/lotteon/service/product/CartService.java, src/main/resources/templates/product/cart.html, src/main/resources/templates/product/view.html
=> cart order

src/main/resources/static/css/my.css, src/main/resources/templates/my/point.html
=> 포인트 페이지네이션

src/main/java/kr/co/lotteon/controller/MyController.java, src/main/resources/templates/my/qna.html
=> 마이페이지-문의하기 1차수정

src/main/java/kr/co/lotteon/controller/MyController.java, src/main/java/kr/co/lotteon/repository/custom/BoardRepositoryCustom.java, src/main/java/kr/co/lotteon/repository/impl/BoardRepositoryImpl.java, src/main/java/kr/co/lotteon/service/my/MyService.java
=> 마이페이지-문의하기 완료

src/main/generated/kr/co/lotteon/entity/admin/QArticle.java, src/main/java/kr/co/lotteon/repository/impl/ProductRepositoryImpl.java, src/main/resources/static/css/product.css, src/main/resources/templates/product/cart.html
=> cartcheck order

src/main/java/kr/co/lotteon/dto/product/ReviewDTO.java, src/main/java/kr/co/lotteon/repository/custom/ProductRepositoryCustom.java, src/main/java/kr/co/lotteon/repository/impl/ProductRepositoryImpl.java, src/main/java/kr/co/lotteon/service/my/MyService.java, src/main/resources/templates/my/review.html
=> 마이페이지-나의 리뷰 작업중(상품명 출력)

src/main/resources/templates/my/review.html
=> 마이페이지-리뷰 별 출력

src/main/java/kr/co/lotteon/dto/product/ReviewDTO.java, src/main/java/kr/co/lotteon/repository/impl/ProductRepositoryImpl.java, src/main/java/kr/co/lotteon/service/my/MyService.java, src/main/resources/templates/my/qna.html, src/main/resources/templates/my/review.html
=> 마이페이지-리뷰,문의하기 view

src/main/java/kr/co/lotteon/controller/MyController.java, src/main/java/kr/co/lotteon/dto/member/point/PointPageRequestDTO.java, src/main/java/kr/co/lotteon/dto/member/point/PointPageResponseDTO.java, src/main/java/kr/co/lotteon/repository/my/PointRepository.java, src/main/java/kr/co/lotteon/service/my/MyService.java, src/main/resources/templates/my/point.html
=> 포인트내역 기간별조회

src/main/java/kr/co/lotteon/controller/CartController.java, src/main/java/kr/co/lotteon/controller/OrderController.java, src/main/java/kr/co/lotteon/controller/ProductController.java, src/main/java/kr/co/lotteon/repository/custom/OrderRepositoryCustom.java, src/main/java/kr/co/lotteon/repository/impl/OrderRepositoryImpl.java, src/main/java/kr/co/lotteon/service/product/CartService.java, src/main/java/kr/co/lotteon/service/product/ProductService.java, src/main/resources/templates/product/cart.html
=> cart -> order

src/main/java/kr/co/lotteon/controller/MyController.java, src/main/resources/static/js/changeInfo.js, src/main/resources/templates/my/infoAccessCheck.html
=> 마이페이지-나의설정 비밀번호 팝업 변경

src/main/java/kr/co/lotteon/controller/MyController.java, src/main/java/kr/co/lotteon/repository/custom/MemberRepositoryCustom.java, src/main/java/kr/co/lotteon/repository/impl/MemberRepositoryImpl.java, src/main/java/kr/co/lotteon/service/member/MemberService.java, src/main/resources/static/js/changeInfo.js, src/main/resources/templates/my/info.html
=> 마이페이지-나의설정 닉네임 따로 변경

src/main/java/kr/co/lotteon/controller/ProductController.java, src/main/resources/static/css/product.css, src/main/resources/templates/product/order.html, src/main/resources/templates/product/view.html
=> cart -> order 끝

src/main/java/kr/co/lotteon/controller/ProductController.java, src/main/java/kr/co/lotteon/dto/product/SearchPageRequestDTO.java, src/main/java/kr/co/lotteon/dto/product/SearchPageResponseDTO.java, src/main/java/kr/co/lotteon/repository/custom/ProductRepositoryCustom.java, src/main/java/kr/co/lotteon/repository/impl/CartRepositoryImpl.java, src/main/java/kr/co/lotteon/repository/impl/ProductRepositoryImpl.java, src/main/java/kr/co/lotteon/service/product/ProductService.java, src/main/resources/templates/layout/csLayout.html, src/main/resources/templates/layout/indexLayout.html, src/main/resources/templates/product/search.html
=> searchKeyword

src/main/java/kr/co/lotteon/controller/MyController.java, src/main/java/kr/co/lotteon/service/member/MemberService.java, src/main/resources/static/css/my.css, src/main/resources/static/js/changeInfo.js, src/main/resources/static/js/popup.js, src/main/resources/templates/my/info.html
=> 나의설정-스크립트 수정완료

src/main/java/kr/co/lotteon/controller/ProductController.java, src/main/java/kr/co/lotteon/dto/product/CartInfoDTO.java, src/main/java/kr/co/lotteon/dto/product/ProductDTO.java, src/main/java/kr/co/lotteon/service/product/ProductService.java, src/main/resources/templates/product/cart.html, src/main/resources/templates/product/view.html
=> 상품 상세보기-> 주문

src/main/resources/templates/cs/index.html, src/main/resources/templates/my/point.html
=> cslayout, point페이지네이션

src/main/java/kr/co/lotteon/config/CacheConfig.java, src/main/java/kr/co/lotteon/controller/MainController.java, src/main/java/kr/co/lotteon/repository/impl/OrderRepositoryImpl.java, src/main/java/kr/co/lotteon/service/product/CateService.java, src/main/java/kr/co/lotteon/service/product/ProductService.java, src/main/resources/templates/product/cart.html, src/main/resources/templates/product/order.html, src/main/resources/templates/product/view.html
=> ordercomplete

src/main/java/kr/co/lotteon/controller/MyController.java, src/main/java/kr/co/lotteon/dto/product/OrderItemDTO.java, src/main/java/kr/co/lotteon/repository/custom/BoardRepositoryCustom.java, src/main/java/kr/co/lotteon/repository/custom/OrderItemRepositoryCustom.java, src/main/java/kr/co/lotteon/repository/custom/PointRepositoryCustom.java, src/main/java/kr/co/lotteon/repository/custom/ProductRepositoryCustom.java, src/main/java/kr/co/lotteon/repository/impl/BoardRepositoryImpl.java, src/main/java/kr/co/lotteon/repository/impl/OrderItemRepositoryImpl.java, src/main/java/kr/co/lotteon/repository/impl/PointRepositoryImpl.java, src/main/java/kr/co/lotteon/repository/impl/ProductRepositoryImpl.java, src/main/java/kr/co/lotteon/service/my/MyService.java, src/main/resources/templates/layout/myLayout.html, src/main/resources/templates/my/home.html
=> 마이페이지 메인-출력 완료

src/main/java/kr/co/lotteon/controller/ProductController.java, src/main/java/kr/co/lotteon/repository/impl/ProductRepositoryImpl.java, src/main/java/kr/co/lotteon/service/product/ProductService.java, src/main/resources/templates/layout/myLayout.html, src/main/resources/templates/layout/productLayout.html, src/main/resources/templates/product/search.html
product 상품클릭시 해당페이지이동, 정렬기능 아직안됨, 검색기능은 구현 다했음
=> product 매핑

src/main/java/kr/co/lotteon/repository/impl/ProductRepositoryImpl.java, src/main/resources/templates/product/search.html
=> product sort

src/main/java/kr/co/lotteon/repository/impl/ProductRepositoryImpl.java, src/main/resources/templates/cs/index.html, src/main/resources/templates/layout/indexLayout.html, src/main/resources/templates/layout/myLayout.html, src/main/resources/templates/layout/productLayout.html, src/main/resources/templates/product/search.html
=> 조회, 페이지네이션

src/main/java/kr/co/lotteon/controller/ProductController.java, src/main/java/kr/co/lotteon/dto/product/OrderItemDTO.java, src/main/java/kr/co/lotteon/repository/impl/OrderItemRepositoryImpl.java, src/main/java/kr/co/lotteon/service/product/ProductService.java, src/main/resources/templates/layout/memberLayout.html, src/main/resources/templates/layout/policyLayout.html, src/main/resources/templates/layout/productLayout.html, src/main/resources/templates/product/complete.html, src/main/resources/templates/product/order.html
뷰-> 주문시 옵션 띄우기
주문 완료 옵션 띄우기
최상단 이동함수 만들기
=> 옵션띄우기, 최상단 이동

src/main/java/kr/co/lotteon/config/WebMvcConfig.java, src/main/java/kr/co/lotteon/controller/ProductController.java, src/main/java/kr/co/lotteon/dto/product/PageRequestDTO.java, src/main/java/kr/co/lotteon/mapper/CouponMapper.java, src/main/java/kr/co/lotteon/repository/custom/CouponRepositoryCustom.java, src/main/java/kr/co/lotteon/repository/impl/CouponRepositoryImpl.java, src/main/java/kr/co/lotteon/repository/my/CouponRepository.java, src/main/java/kr/co/lotteon/service/product/ProductService.java, src/main/resources/mappers/coupon.xml, src/main/resources/static/css/product.css, src/main/resources/templates/layout/indexLayout.html, src/main/resources/templates/layout/productLayout.html, src/main/resources/templates/product/complete.html, src/main/resources/templates/product/list.html, src/main/resources/templates/product/order.html
=> css, 쿠폰 사용하기

src/main/java/kr/co/lotteon/config/WebMvcConfig.java, src/main/resources/static/js/order.js, src/main/resources/templates/cs/qna/write.html, src/main/resources/templates/layout/indexLayout.html, src/main/resources/templates/layout/productLayout.html, src/main/resources/templates/product/search.html
=> 검색어제한, cs유형선택필수

src/main/java/kr/co/lotteon/config/WebMvcConfig.java, src/main/java/kr/co/lotteon/controller/MemberController.java, src/main/java/kr/co/lotteon/repository/impl/CouponRepositoryImpl.java, src/main/java/kr/co/lotteon/service/member/MemberService.java, src/main/resources/mappers/coupon.xml
=> 회원가입시 쿠폰 지급
